# Generated by Django 5.0.2 on 2024-02-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='technology',
            field=models.ManyToManyField(blank=True, to='api.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, to='api.technology'),
        ),
    ]
