# Generated by Django 5.0.2 on 2024-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_technology_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='images/18961868.jpg', upload_to='images/'),
        ),
    ]
