# Generated by Django 5.0.2 on 2024-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/18961868.jpg', upload_to='images/'),
        ),
    ]
