# Generated by Django 5.0.2 on 2024-03-11 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
