# Generated by Django 5.0.2 on 2024-03-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_experiencedescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedescription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='experiencedescription',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='experiencedescription',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='experiencedescription',
            name='modified_by',
        ),
    ]
