# Generated by Django 5.0.2 on 2024-03-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_experiencedescription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_description',
        ),
        migrations.DeleteModel(
            name='ExperienceDescription',
        ),
    ]
